# Site settings
title: Yanna Lin
email: yanna.lin@uwaterloo.ca
description: > # this means to ignore newlines until "baseurl:"
   A Postdoc at UWaterloo working on data visualization and hci.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.yannahhh.github.io" # the base hostname & protocol for your site
production_url: "https://www.domoritz.de"
github_username: Yannahhh
permalink: /blog/:year/:month/:title.html

twitter:
  username: yanna

sass:
  style: compressed

collections:
  publications:
    output: false

jekyll-mentions:
  base_url: https://twitter.com


avatar: "./assets/img/avatar-icon.png"
round-avatar: true

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-sitemap
